### ISSUE TITLE
validation for creating blog not working

### ISSUE THREAD

**Issue by foliwe** [jordanhudgens/devcamp-portfolio#12]
When trying to create an empty blog, you have this error

### undefined method `each' for nil:NilClass
              
  <div class="sidebar-module">

    ***<% @side_bar_topics.each do |topic| %>***

      <p><%= link_to topic.title, topic_path(topic) %></p>
    <% end %>
  </div>

**Comment by hamza2000a** [comment]
The error clearly complaints that you're calling each method on something here(@posts) which is nil. That means you've not defined it in your controller. Since you didn't define it, that's why it is complaining undefined method for nil class.

Please makes sure to check whenever you call an instance variable from your view? you must have to define that in your controller to be accessible in views.

Sometimes you'll also get this error if you call a private method in your controller.

**Comment by dohkim** [comment]
reason why @side_bar_topics is nil..is  issue happened in create action.
but set_sidebar_topics excepts create action so delete create in except list.
```
 before_action :set_sidebar_topics, except: [:update, :create, :destroy, :toggle_status] ->  before_action :set_sidebar_topics, except: [:update, :destroy, :toggle_status]

**Comment by foliwe** [comment]
thanks
